task 04
js-tasks-ru/nodejs-20220303_nishkrut pull request #4
Opened 2022-03-20 20:35 UTC by NefedovNick

2022-03-20 20:37 UTC, jsru commented
Добавляю преподавателя (@tadjik1) для код-ревью.

2022-03-23 20:48 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @tadjik1

2022-03-27 20:27 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @tadjik1

2022-03-31 09:46 UTC, tadjik1 commented on 05-koajs/01-chat-app/app.js
> +  for (const res of resolvers) {
по окончании перебора всех клиентов надо удалять (очищать массив)

2022-03-31 09:47 UTC, tadjik1 requested changes
@NefedovNick  все задачи решены абсолютно верно, небольшой нюанс в задаче про чат касается удаления всех клиентов, его нужно поправить

2022-04-02 11:53 UTC, jsru commented
Добавляю преподавателя (@tadjik1) для код-ревью.

2022-04-02 11:55 UTC, NefedovNick commented on 05-koajs/01-chat-app/app.js
> +  for (const res of resolvers) {
Здравствуйте, Сергей! Спасибо за указание на ошибку - поправил. Можно попросить вас затронуть тему, как Вы называете коммиты (задачи и фиксы), у меня какой-то рандом, думаю, что у многих мб также. Либо ссылку мб дать, где есть какие-то практики

2022-04-02 15:01 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @tadjik1

2022-04-03 13:26 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @tadjik1

2022-04-03 15:19 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @tadjik1

2022-04-03 15:21 UTC, NefedovNick commented
у меня нету соц. сети вк. Я поменял в тесте на github (вообще, странно, что сделали проверку для вк). 
еще меня удивила проверка на ошибку - 
        expect(err.name).to.equal('ValidationError');
        expect(err.errors.email.message).to.equal('Некорректный email.');
пришлось создавать свой объект ошибки, так и задумано было?

2022-04-03 19:20 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-04-10 12:48 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @tadjik1

2022-04-10 19:05 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @tadjik1

2022-04-11 13:45 UTC, tadjik1 approved these changes
Отличные решения! И спасибо за ваши вопросы, обязательно на занятии отвечу.
По поводу вк - вы абсолютно правы, я не вижу больше смысла его вообще упоминать в курсе. Думаю что вариант с GitHub будет намного лучше со всех точек зрения (тем более что мы его и используем на курсе).

2022-04-11 13:49 UTC, merged